@host = http://localhost:3000

GET  {{host}}/api/alumnos/profesores
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo5NiwidXN1YXJpb19yb2wiOiJhbHVtIiwiZXhwIjoxNjg3MjE5OTE3LCJpYXQiOjE2ODcxMzM1MTd9.5HUKgs4_--r3j_E-Wd_Bp8m0A0qSZQgUuM9OCUP0Nfw

###

POST  {{host}}/api/usuarios/login
Content-Type: application/json

{
    "email": "sara@gmail.com",
    "password": "12345"
}

###

POST  {{host}}/api/usuarios/registro
Content-Type: application/json

{
    "nombre": "Benjamin", 
    "apellidos": "Luzon",
    "username": "Nezarlc",
    "telefono": 608561642,
    "dni": "77024991Z",
    "rol": "profe",
    "direccion": "Calle sur",
    "ciudad": "Granada",
    "edad": 22,
    "fecha_nacimiento": "2023-05-11",
    "genero": "m",
    "email": "benjaluzon03@gmail.com",
    "password": "hola",
    "experiencia": 3,
    "precio": 4
}

###

GET {{host}}/api/alumnos/clasesActivas
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMCwidXN1YXJpb19yb2wiOiJhbHVtIiwiZXhwIjoxNjg2NDk1MTQwLCJpYXQiOjE2ODY0MDg3NDB9.M5XBc-1EzG4jW--j1WOGMZJSDdGu6_-dQBIPBSaO6BE


###

GET {{host}}/api/alumnos/clases
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMSwidXN1YXJpb19yb2wiOiJhbHVtIiwiZXhwIjoxNjg2NDk4MzA0LCJpYXQiOjE2ODY0MTE5MDR9.Xs1jeGMOr-sOY3KuFoWZhu38MogLT3cvwpKxyUWZHKE

###

PUT {{host}}/api/clases/claseProfesorAlumno
Content-Type: application/json

{
    "profesor_id": "2",
    "asignatura_id": "2",
    "alumno_id": "8"
}

### 

DELETE {{host}}/api/clases/9