@host = http://localhost:3000

GET {{host}}/api/asignaturas/filtro
Content-Type: application/json

{
    "rama": "Ciencias",
    "nombre": "Historia"
}


###

GET {{host}}/api/clases/media/1

###

GET {{host}}/api/alumnos/
Content-Type: application/json

{
    "rama": "Ciencias",
    "nombre": "Historia"
}


###

GET {{host}}/api/asignaturas/3

###

POST  {{host}}/api/clases
Content-Type: application/json

{
    "profesor_id": "1",
    "asignatura_id": "1",
    "alumno_id": "7",
    "puntuacion": "8",
    "opinion": "Este profesor sabe de lo que habla."
}

### 

DELETE {{host}}/api/clases/9